### PR TITLE
test: correcting existing tests

### PR DESCRIPTION
**Pull request by csgaikwad**
## What does this PR do?

This PR addresses unresolved conversations and comments related to cal.com issue #15712, following up on the PR created by @rajeshj11. Note that this PR does not fix the issue itself but rather addresses feedback from the previous PR.

Addresses: Unresolved comments from PR #15715 (GitHub PR number).
image

## Mandatory Tasks (DO NOT REMOVE)

- [X ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [X ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ X] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by rajesh-jonnalagadda** [comment]
@csgaikwad yarn. lock and .env files should not be added. add the required files at the stage level and then do commit.

In your case, it only has test-related files. other files ignore and while committing.

**Comment by rajesh-jonnalagadda** [comment]
Screenshot from 2024-08-05 08-26-28
also can you please check this?

run yarn test

**Comment by csgaikwad** [comment]
> @csgaikwad yarn. lock and .env files should not be added. add the required files at the stage level and then do commit.
> 
> In your case, it only has test-related files. other files ignore and while committing.

Ok I'll do that.

**Comment by rajesh-jonnalagadda** [comment]
> > @csgaikwad yarn. lock and .env files should not be added. add the required files at the stage level and then do commit.
> > In your case, it only has test-related files. other files ignore and while committing.
> 
> Ok I'll do that.

I have already moved the test files to that place and tests are running now.

**Pull request closed without merging**
